### PR TITLE
My solution to the problem 'Bigger is Greater'

### PR DESCRIPTION
**Pull request by cherryWood55**
I have added the code for the problem 'Bigger is Greater' using C++.
The above code has successfully run in Dev C++ compiler.
The work has solved #9 issue.

### CODE REVIEW

**Comment by Sayan-dev** [comment]
congrats...its working fine....awssom

**Comment by jddeep** [comment]
@cherryWood55 Please provide the PR description. Follow #4 pattern

**Comment by cherryWood55** [comment]
> 
> 
> @cherryWood55 Please provide the PR description. Follow #4 pattern

Added. Please review.

**Review by jddeep — APPROVED** [review]
Nice work :+1:

**Pull request merged**
